# Generated by Django 6.0.6 on 2026-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
