# Generated by Django 6.0.6 on 2026-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_match_date_utc_match_halftime_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='analysis_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='analysis_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
